name: Backend

on:
  push:
    branches:
      - develop
      - master
      - feature/*
      - gh-pages
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          cd ..
          ls -la
          sudo chmod 777 ~/demo4/deploy.sh
          sh deploy.sh

