name: Backend

on:
  push:
    branches:
      - develop
      - master
      - feature/*
      - gh-pages
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Deploy
        run: |
          npm install -g sass 
          npm install
          npm run build

