name: Backend

on:
  push:
    branches:
      - develop
      - master
      - feature/*
      - gh-pages
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          npm run build

